spring:
  liquibase:
    enabled: true
    change-log: 'db-migrations/changelog.xml'
  datasource:
    url: "jdbc:postgresql://localhost:5432/testusers?currentSchema=testusers"
    username: testuser_admin
    password: testuser_admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none